---

- hosts: all
  become: true
  tasks: 

  - name: install apache2 and php
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: true
    when: ansible_distribution == "AlmaLinux"
