---

- hosts: all
  become: true
  tasks: 

  - name: install updates (Alma)
    dnf:
      update_only: true
      update_cache: true
    when: ansible_distribution == "AlmaLinux"

  - name: instal updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu
    apt: 
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Alma
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "AlmaLinux"

- hosts: db_servers
  become: true
  tasks:
    - name: install MariaDB (AlmaLinux)
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "AlmaLinux"

    - name: install MariaDB (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      package:
        name: samba
        state: latest

