---

- hosts: all
  become: true
  pre_tasks: 

  - name: install updates (Alma)
    tags: always
    dnf:
      update_only: true
      update_cache: true
    when: ansible_distribution == "AlmaLinux"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
    - name: create simone user
      tags: always
      user:
        name: simone
        groups: root

- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      tags: unzip
      package:
        name: unzip

    - name: install terraform
      tags: terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.8.0/terraform_1.8.0_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu
    tags: apache,apache2,ubuntu
    apt: 
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Alma
    tags: apache,httpd,almalinux 
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: start httpd (AlmaLinux)
    tags: apache,almalinux,httpd
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "AlmaLinux"

  - name: change email address
    tags: apache,almalinux,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin martin.allen@exe-squared.co.uk
    when: ansible_distribution == "AlmaLinux"
    register: httpd

  - name: restart httpd
    tags: apache,almalinux,httpd
    service: 
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: install MariaDB (AlmaLinux)
      tags: almalinux,db,mariadb
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "AlmaLinux"

    - name: install MariaDB (Ubuntu)
      tags: mariadb,db,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest

